name: imageclassification
description: trying to understand how it is work
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image: ^3.0.2
  tflite_flutter: ^0.9.1
  image_picker: ^0.8.7+3
  collection: ^1.17.0
  logger: ^1.3.0
  path_provider:
  camera: ^0.10.4
  tuple: ^2.0.1
  quiver: ^3.2.1
  tflite_flutter_helper: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/